/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Song;

import javax.swing.JOptionPane;

/**
 *
 * @author joshuatupas
 */
public class MusicGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicGUI
     */
    Playlist playlist;
    Playlist rapMusic;
    Playlist popMusic;
    public MusicGUI() {
        popMusic = new Playlist ();
        rapMusic = new Playlist ();
        playlist = new Playlist ();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        artistTF = new javax.swing.JTextField();
        titleTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        printMusics = new javax.swing.JButton();
        countSongs = new javax.swing.JButton();
        moveBTN = new javax.swing.JButton();
        genreCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        createBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rapTA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        popTA = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel2.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel2.setText("Artist:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));
        jPanel2.add(artistTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 30));
        jPanel2.add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, 30));

        jLabel3.setText("Title:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        printMusics.setText("Print");
        printMusics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMusicsActionPerformed(evt);
            }
        });
        jPanel2.add(printMusics, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        countSongs.setText("Size");
        countSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countSongsActionPerformed(evt);
            }
        });
        jPanel2.add(countSongs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        moveBTN.setText("Move");
        moveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBTNActionPerformed(evt);
            }
        });
        jPanel2.add(moveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        genreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Rap" }));
        jPanel2.add(genreCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));

        jLabel1.setText("Genre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        jPanel2.add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));
        jPanel2.add(searchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 120, 30));

        createBTN.setText("Create Playlist");
        createBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTNActionPerformed(evt);
            }
        });
        jPanel2.add(createBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        jTabbedPane1.addTab("Liked Songs", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rapTA.setColumns(20);
        rapTA.setRows(5);
        jScrollPane1.setViewportView(rapTA);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 770, 250));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("Rap Musics");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel4)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        jTabbedPane1.addTab("Rap", jPanel3);

        popTA.setColumns(20);
        popTA.setRows(5);
        popTA.setPreferredSize(new java.awt.Dimension(200, 90));
        jScrollPane2.setViewportView(popTA);

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Pop Musics");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel5)
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pop", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        if (artistTF.getText().isEmpty() == true || titleTF.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , "Please enter the title and the artist.");
        } else {
            playlist.addMusic();
        }

    }//GEN-LAST:event_addBTNActionPerformed

    private void moveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBTNActionPerformed
        playlist.moveToGenre();
    }//GEN-LAST:event_moveBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        if (playlist.isEmpty()) {
            JOptionPane.showMessageDialog(null , "The playlist is empty");
        } else {
            playlist.removeMusic();
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void countSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countSongsActionPerformed
        if (playlist.isEmpty()) {
            JOptionPane.showMessageDialog(null , "The playlist is empty");
        } else {
            int count = playlist.countMusic();
            JOptionPane.showMessageDialog(null, "There are " + count + " songs in the playlist.");
        }
    }//GEN-LAST:event_countSongsActionPerformed

    private void printMusicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMusicsActionPerformed
    if (playlist.isEmpty()) {
        JOptionPane.showMessageDialog(null, "The playlist is empty.");
    } else {
        playlist.printList();
    }
    }//GEN-LAST:event_printMusicsActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        playlist.searchMusic();
    }//GEN-LAST:event_searchBTNActionPerformed

    private void createBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTNActionPerformed
        playlist.createPlaylist();
    }//GEN-LAST:event_createBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addBTN;
    public static javax.swing.JTextField artistTF;
    private javax.swing.JButton countSongs;
    private javax.swing.JButton createBTN;
    private javax.swing.JButton deleteBTN;
    public static javax.swing.JComboBox<String> genreCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton moveBTN;
    public static javax.swing.JTextArea popTA;
    private javax.swing.JButton printMusics;
    public static javax.swing.JTextArea rapTA;
    private javax.swing.JButton searchBTN;
    public static javax.swing.JTextField searchTF;
    public static javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
